apiVersion: v1
kind: Service
metadata:
  name: micro-auth
  namespace: default
  labels:
    micro: runtime
    name: auth
    version: latest
spec:
  ports:
  - port: 8010
    protocol: TCP
  selector:
    name: micro-auth
    micro: runtime
