apiVersion: v1
kind: Service
metadata:
  name: micro-events
  namespace: default
  labels:
    micro: runtime
    name: events
    version: latest
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    name: micro-events
    micro: runtime
