apiVersion: v1
kind: Service
metadata:
  name: micro-proxy
  namespace: default
  labels:
    micro: runtime
    name: proxy
    version: latest
spec:
  ports:
  - name: https
    port: 443
    targetPort: 443
  - name: proxy
    port: 8081
    targetPort: 8081
  selector:
    name: micro-proxy
    micro: runtime
  type: LoadBalancer
