apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: micro-proxy-latest
  labels:
    micro: runtime
    name: proxy
    version: latest
  annotations:
    name: "proxy"
    version: "latest"
    source: "github.com/micro/micro"
    owner: "micro"
    group: "micro"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: micro-proxy
      micro: runtime
  template:
    metadata:
      labels:
        name: micro-proxy
        micro: runtime
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "9000"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: name
                      operator: In
                      values:
                        - micro-proxy
                    - key: micro
                      operator: In
                      values:
                        - runtime
                topologyKey: "kubernetes.io/hostname"
      containers:
      - name: micro
        env:
        - name: MICRO_PROXY
          value: "micro-network.default.svc.cluster.local:8443"
        - name: MICRO_SERVICE_NAME
          value: client
        - name: MICRO_AUTH_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: micro-secrets
              key: auth_public_key
        - name: MICRO_AUTH_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: micro-secrets
              key: auth_private_key
        - name: MICRO_PROFILE
          value: "client"
        - name: MICRO_PROXY_ADDRESS
          value: "0.0.0.0:443"
        - name: MICRO_LOG_LEVEL
          value: "trace"
        - name: MICRO_ENABLE_ACME
          value: "true"
        - name: MICRO_ACME_PROVIDER
          value: certmagic
        - name: MICRO_ACME_HOSTS
          value: 'proxy.m3o.com'
        - name: CF_API_TOKEN
          valueFrom:
            secretKeyRef:
              key: cloudflare
              name: micro-secrets
        args:
        - service
        - proxy
        image: micro/platform
        imagePullPolicy: Always
        ports:
        - containerPort: 443
          name: https-port
        - containerPort: 8081
          name: proxy-port
        readinessProbe:
          tcpSocket:
            port: https-port
          initialDelaySeconds: 5
          periodSeconds: 10
