apiVersion: v1
kind: Service
metadata:
  name: micro-router
  namespace: default
  labels:
    micro: runtime
    name: router
    version: latest
spec:
  ports:
  - port: 8084
    protocol: TCP
  selector:
    name: micro-router
    micro: runtime
