apiVersion: v1
kind: Service
metadata:
  name: micro-runtime
  namespace: default
  labels:
    micro: runtime
    name: runtime
    version: latest
spec:
  ports:
  - port: 8088
    protocol: TCP
  selector:
    name: micro-runtime
    micro: runtime
