apiVersion: v1
kind: Service
metadata:
  name: micro-store
  namespace: default
  labels:
    name: micro-store
    micro: runtime
spec:
  ports:
  - port: 8002
    protocol: TCP
  selector:
    name: micro-store
    micro: runtime
