name: Generate Client SDKs

on:
 schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 09 * * *'

jobs:
  generate:
    name: generate clients
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out the code
      uses: actions/checkout@v2

    - name: Generate Clients
      run: |
        ./scripts/generate-clients.sh

    - name: Commit Changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add client/sdk/ && git commit -m "Regenerate client sdks from proto" || true

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
