name: CI Profile
on: [push]

jobs:

  test:
    name: Integration tests
    runs-on: ubuntu-latest
    env: 
      DOCKER_BUILDKIT: '1'
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v2
      with:
        go-version: 1.13
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    # http://man7.org/linux/man-pages/man1/date.1.html
    - name: Get Date
      id: get-date
      run: |
        echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
      shell: bash
    - name: Enable caching
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-int-${{ steps.get-date.outputs.date }}

    - name: Install Protoc
      uses: arduino/setup-protoc@master

    - name: Install Protoc Gen Micro
      working-directory: ./cmd/protoc-gen-micro
      run: go install

    - name: Install Protoc Gen Go
      run: go get -u github.com/golang/protobuf/protoc-gen-go

    - name: Replace CI profile
      id: replace-profile
      run: |
        go mod edit -replace github.com/micro/micro/profile/ci/v3=./profile/ci
        go mod edit -replace google.golang.org/grpc=google.golang.org/grpc@v1.26.0

    # Install micro binary and then build micro with the profile inside a tmp directory. We do this
    # to not alter the original go.mod & go.sum, which the test services reference directly with 
    # replace statements. TODO: find a simpler way of achieving this.
    - name: Install micro
      id: install-micro
      run: |
        go install
        out=$(pwd)/micro
        mkdir /tmp/micro
        cp -R . /tmp/micro
        cd /tmp/micro
        micro init --profile=ci --output=profile.go
        GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o $out
    
    # This sets up a local docker registry to push and pull our test docker image so that we can persist 
    # Based on https://dev.to/dtinth/caching-docker-builds-in-github-actions-which-approach-is-the-fastest-a-research-18ei
    - name: Setup docker caching
      id: cache-docker
      uses: actions/cache@v2
      with:
        path: /tmp/docker-registry
        key: docker-registry-int-${{ steps.get-date.outputs.date }}
    - name: Setup docker registry
      run: |
        docker run -d -p 5000:5000 --restart=always --name registry -v /tmp/docker-registry:/var/lib/registry registry:2 && npx wait-on tcp:5000
    - name: Build docker image
      run: |
        docker build -f test/Dockerfile . -t micro --cache-from=localhost:5000/micro --build-arg BUILDKIT_INLINE_CACHE=1
    - name: Tag and push docker
      run: |
        docker tag micro localhost:5000/micro && docker push localhost:5000/micro || true

    - name: Check out services
      uses: actions/checkout@v2
      with:
        repository: 'micro/services'
        path: 'test/services'

    - name: Delete go mod
      working-directory: ./test
      run: |
        rm ./services/go.mod
        rm ./services/go.sum
        rm -rf ./services/.git
  
    - name: Replace paths
      working-directory: ./test/services
      run: |
        grep -rl github.com/micro/services . | xargs sed -i 's/github.com\/micro\/services/github.com\/micro\/micro\/v3\/test\/services/g'

    - name: Test micro server
      working-directory: ./test
      env:
        GITHUB_PAT: ${{ secrets.MICRO_ACTIONS_PAT }}
        GITLAB_PAT: ${{ secrets.GITLAB_PAT }}
      run: |
        go clean -testcache && go test --tags=integration -v -run ./... -timeout 20m
